class Nigeria {
  static const List<String> universities = [
    "Abia State University",
    "Abubakar Tafawa Balewa University",
    "Achievers University, Owo",
    "Adamawa State University",
    "Adekunle Ajasin University",
    "Adeleke University",
    "Afe Babalola University",
    "Ahmadu Bello University",
    "Ajayi Crowther University",
    "Akwa Ibom State University",
    "Al-Hikmah University",
    "Al-Qalam University, Katsina",
    "Ambrose Alli University",
    "American University of Nigeria",
    "Babcock University",
    "Bauchi State University",
    "Bayero University Kano",
    "Baze University",
    "Bells University of Technology",
    "Benson Idahosa University",
    "Benue State University",
    "Bingham University",
    "Borno State University",
    "Bowen University",
    "Caleb University",
    "Caritas University",
    "Chrisland University",
    "Chukwuemeka Odumegwu Ojukwu University",
    "Clifford University",
    "Coal City University",
    "Covenant University",
    "Crawford University",
    "Crescent University, Abeokuta",
    "Cross River University of Technology",
    "Crown Hill University",
    "Delta State University, Abraka",
    "Dominican University, Ibadan",
    "Eastern Palm University",
    "Ebonyi State University",
    "Edo University",
    "Edwin Clark University",
    "Ekiti State University, Ado Ekiti",
    "Eko University of Medical and Health Sciences",
    "Elizade University",
    "Enugu State University of Science and Technology",
    "Evangel University Akaeze",
    "Federal University of Agriculture, Abeokuta",
    "Federal University of Petroleum Resources",
    "Federal University of Technology, Akure",
    "Federal University of Technology, Minna",
    "Federal University of Technology, Owerri",
    "Federal University, Birnin Kebbi",
    "Federal University, Dutse",
    "Federal University, Dutsin-Ma",
    "Federal University, Gashua",
    "Federal University, Gusau",
    "Federal University, Kashere",
    "Federal University, Lafia",
    "Federal University, Lokoja",
    "Federal University, Ndufu-Alike ",
    "Federal University, Otuoke",
    "Federal University, Oye-Ekiti",
    "Federal University, Wukari",
    "Fountain University",
    "Gombe State University",
    "Gombe State University of Science and Technology",
    "brahim Badamasi Babangida University",
    "Igbinedion University Okada",
    "Imo State University",
    "Kaduna State University",
    "Kano University of Science and Technology",
    "Kebbi State University of Science and Technology",
    "Kings University",
    "Kogi State University",
    "Kwara State University",
    "Ladoke Akintola University of Technology",
    "Lagos State University",
    "Landmark University",
    "Lead City University",
    "Madonna University, Okija",
    "Mountain Top University",
    "Nasarawa State University",
    "Niger Delta University",
    "Nile University of Nigeria",
    "Nnamdi Azikiwe University",
    "Northwest University Kano",
    "Obafemi Awolowo University",
    "Ondo State University of Science and Technology",
    "Osun State University",
    "Pan African University",
    "Plateau State University",
    "Redeemer's University",
    "Rivers State University of Science and Technology",
    "Sokoto State University",
    "Taraba State University",
    "Umaru Musa Yar'Adua University",
    "University of Abuja",
    "University of Africa",
    "University of Agriculture, Makurdi",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Medical Sciences",
    "University of Nigeria",
    "University of Port Harcourt",
    "University of Uyo",
    "Usmanu Danfodio University",
    "Veritas University",
    "Western Delta University",
    "Yobe State University",
  ];

  static const List<String> polytechnics = [
    "Air Force Institute of Technology, Kaduna, Kaduna State",
    "Federal Polytechnic, Auchi, Edo State",
    "Federal Polytechnic, Ado-Ekiti, Ekiti State",
    "Akanu Ibiam Federal Polytechnic, Unwana, Ebonyi State",
    "Federal Polytechnic, Bali, Taraba State",
    "Federal Polytechnic, Bauchi, Bauchi State",
    "Federal Polytechnic, Bida, Niger State",
    "Federal Polytechnic, Damaturu, Yobe State",
    "Federal Polytechnic, Ede, Osun State",
    "Federal Polytechnic, Ekowe, Bayelsa State",
    "Federal Polytechnic, Idah Kogi State",
    "Federal Polytechnic, Ilaro, Ogun State",
    "Federal Polytechnic, Mubi, Adamawa State",
    "Federal Polytechnic, Kaura/Namoda, Zamfara State",
    "Federal Polytechnic, Nasarawa, Nasarawa State",
    "Federal Polytechnic, Nekede, Owerri, Imo State",
    "Federal Polytechnic, Offa, Kwara State",
    "Federal Polytechnic, Oko, Orumba North L.G.A, Anambra State",
    "Federal Polytechnic, Ile-Oluji, Ondo State",
    "Federal Polytechnic, Ukana, Essien Udim, Akwa Ibom State",
    "Federal School of Dental Technology and Therapy, Enugu, Enugu State",
    "Kaduna Polytechnic, Kaduna, Kaduna State",
    "Hussaini Adamu Federal Polytechnic, Kazaure, Jigawa State",
    "Nigeria Army Institute of Technology and Environmental Studies, Makurdi, Benue State",
    "National Institute for Construction Technology, Uromi, Edo State",
    "Waziri Umaru Federal Polytechnic Birnin Kebbi, Kebbi State",
    "Yaba College of Technology, Yaba, Lagos State",
    "Abraham Adesanya Polytechnic, Ijebu-Igbo, Ogun State Nigeria",
    "Abia State Polytechnic, Aba, Abia State",
    "Abia State College of Health Sciences and Management Technology, Aba, Abia State",
    "Abdu Gusau Polytechnic, Talata-Mafara, Zamfara State",
    "Akwa-Ibom State Polytechnic, Ikot-Osurua, Ikot-Ekpene, Akwa-Ibom State",
    "Mai Idris Alooma Polytechnic, Geidam, Yobe State",
    "Akwa Ibom State College of Arts and Science Nung, Ukim, Akwa Ibom State",
    "Abubakar Tatari Ali Polytechnic, Bauchi, Bauchi State",
    "Benue State Polytechnic, Ugbokolo, Benue State",
    "Binyaminu Usman College of Agriculture, Hadejia, Jigawa State",
    "Bayelsa State College of Arts and Science, Elebele, Bayelsa State",
    "College of Administrative and Business Studies, Potiskum, Yobe State",
    "College of Health Sciences and Technology, Ijero-Ekiti, Ekiti State",
    "D. S. Adegbenro ICT Polytechnic, Itori, Ogun State",
    "Enugu State Polytechnic, Iwollo, Ezeagu LGA, Enugu State",
    "The Polytechnic, Ibadan, Oyo State",
    "Imo State Polytechnic, Umuagwo, Ohaji, Imo State Nigeria",
    "Institute of Management and Technology, Enugu, Enugu State",
    "Institute of Technology and Management, Ugep, Cross River State",
    "Jigawa State Polytechnic, Dutse Jigawa State",
    "Kano State Polytechnic, Kano, Kano State",
    "Hassan Usman Katsina Polytechnic, Katsina, Katsina State",
    "Kogi State Polytechnic, Lokoja, Kogi State",
    "College of Business and Management Studies, Konduga, Borno State",
    "Kwara State Polytechnic, Ilorin, Kwara State",
    "Lagos State Polytechnic, Ikorodu, Lagos State",
    "Moshood Abiola Polytechnic, Abeokuta, Ogun State",
    "Nasarawa State Polytechnic, Lafia,  Nasarawa State",
    "Nuhu Bamalli Polytechnic, Zaria, Kaduna State",
    "Delta State Polytechnic, Ogwashi-Uku, Delta State",
    "Ogun State Institute of Technology, (formerly Gateway ICT Polytechnic), Igbesa, Ogun State",
    "The Oke-Ogun Polytechnic, Saki, Oyo State",
    "Delta State Polytechnic, Otefe, Delta State",
    "Osun State Polytechnic, Iree, Osun State",
    "Osun State College of Tech, Esa-Oke, Osun State",
    "Delta State Polytechnic, Ozoro, Delta State",
    "Port Harcourt Polytechnic, Rumuola, River State",
    "Plateau State Polytechnic, Barkin-Ladi, Plateau State",
    "Adamawa State Polytechnic, Yola, Adamawa State",
    "Ramat Polytechnic, Maiduguri, Borno State",
    "Rivers State College of Health Science, Rumueme, River State",
    "Rufus Giwa Polytechnic, Owo, Ondo State",
    "Gateway ICT Polytechnic, Saapade, Ogun State",
    "Kenule Beeson Saro-Wiwa Polytechnic, Bori, Rivers State",
    "Taraba State Polytechnic, Suntai, Taraba State",
    "The Ibarapa Polytechnic, Eruwa, Oyo State",
    "Umar Ali Shinkafi Polytechnic, Farfaru, Sokoto State",
    "Edo State Institute of Technology and Management, Usen, Edo State",
    "Niger State Polytechnic, Zungeru, Niger State",
    "Ajayi Polytechnic, Ikere-Ekiti, Ekiti State",
    "Al-Hikma Polytechnic, Karu, Nasarawa State",
    "Allover Central Polytechnic, Ota, Ogun State",
    "Bolmor Polytechnic, Agodi, Ibadan, Oyo State",
    "Best Solution Polytechnic, Akure, Ondo State",
    "Calvary Polytechnic, Owo-Oyibo, Delta State",
    "Covenant Polytechnic, Aba, Abia State",
    "Crown Polytechnic, Odo Ado-Ekiti, Ekiti State",
    "College of Technology, Iresi, Boluwaduro L.G.A., Osun State",
    "Dorben Polytechnic, Bwari-Garam Road, Abuja FCT",
    "Eastern Polytechnic, Rumuokwurusi, Port Harcourt, Rivers State",
    "Fidei Polytechnic, Gboko, Benue State",
    "Gboko Polytechnic, Gboko, Benue State",
    "Global Polytechnic, Akure, Ondo State",
    "Grace Polytechnic, Surulere, Lagos State",
    "Heritage Polytechnic, Ikot Udota, Akwa Ibom State",
    "Ibadan City Polytechnic, Dugbe, Ibadan, Oyo State",
    "Igbajo Polytechnic, Igbajo, Osun State",
    "The Polytechnic, Igbo-Owu, Ilorin Kwara State",
    "The Polytechnic, Ile-Ife, Ile-Ife, Osun State",
    "Interlink Polytechnic, Ijebu-Jesa, Osun State",
    "Kalac Christal Polytechnic, Sango-Tedo, Lekki, Lagos State",
    "Kings Polytechnic, Ubiaja, Edo State",
    "Lagos City Polytechnic, Ikeja, Lagos State",
    "Lens Polytechnic,Offa, Kwara State",
    "Light House Polytechnic, Evbuobanosa, Edo State",
    "Marist Polytechnic, Umuchigbo-De Nike Emene, Enugu, Enugu State",
    "NACABS Polytechnic, Akwanga, Nasarawa State",
    "Nogak Polytechnic, Ikom, Cross River State",
    "Our Saviour Institute of Science and Technology (Poly) Enugu, Enugu State",
    "The Polytechnic, Imesi-Ile, Osun State",
    "The Polytechnic, Adoka, Benue State",
    "Prime Polytechnic, Jidda Bassa, Ajaokuta, Kogi State",
    "RONIK Polytechnic, Alimosho, Lagos State",
    "Shaka Polytechnic, Ogiso, Benin City, Edo State",
    "St. Mary Polytechnic, Kwamba, Suleja, Niger State",
    "Sure Foundation Polytechnic, Ikot Akai, Akwa Ibom State",
    "Temple-Gate Polytechnic, Osisioma, Abia State",
    "Tower Polytechnic, Ibadan, Oyo State",
    "Trinity Polytechnic, Ifa Arai, Uyo, Akwa Ibom State",
    "Uma Ukpai Polytechnic, Osaga Ohafia, Abia State",
    "Uyo City Polytechnic, Uyo, Akwa Ibom State",
    "Valley View Polytechnic, Ohafia, Abia State",
    "Wolex Polytechnic, Dopemu, Lagos State",
  ];

  static const List<String> healthSciences = [
    "Ahmadu Bello University Teaching Hospital P.M.B. , Shika, Zaria, Kaduna State",
    "Aminu Kano Teaching Hospital, School of Health Information Management, Kano, Kano State",
    "School of Health Information Management, Lagos University Teaching Hospital, Idi-Araba, Lagos State",
    "School of Health Information Management, Obafemi Awolowo University Teaching Hospital Complex, Ile-Ife, Osun State",
    "Shehu Idris College of Health Sciences and Technology, Makarfi, Kaduna State",
    "School of Health Information Management, University of Benin Teaching Hospital, Benin City, Edo State",
    "School of Health Information Management, University College Hospital, Ibadan, Oyo State",
    "School of Health Information Management, University of Maiduguri Teaching Hospital, Maiduguri, Borno State",
    "University of Ilorin Teaching Hospital, School of Health Information Management, Ilorin, Kwara State",
    "School of Health Information Management, University of Uyo Teaching Hospital, Uyo, Akwa Ibom State",
    "University of Calabar Teaching Hospital, School of Health Information Management, Calabar",
    "University of Port Harcourt Teaching Hospital, Port Harcourt, Rivers State",
    "School of Health Information Management, Nnamdi Azikiwe University Teaching Hospital, Nnewi, Anambra State",
  ];

  static const List<String> collegeOfEducation = [
    "Federal College of Education (Technical), Asaba",
    "Federal College of Education, Kano",
    "Federal College of Education (Special), Oyo",
    "College of Education, Gindiri",
    "College of Education, Hong",
    "Tai Solarin College of Education, Ijebu-Ode",
    "College of Education, Ikere-Ekiti",
    "Ebonyi State College of Education, (T) Ikwo",
    "College of Education, Warri",
    "FCT College of Education, Zuba",
    "Delar College of Education",
    "Federal College of Education, Abeokuta",
    "Federal College of Education, Eha-Amufu",
    "Federal College of Education (Technical), Gombe",
    "Federal College of Education, Kontagora",
    "Federal College of Education, Okene",
    "Federal College of Education (Technical), Omoku",
    "Federal College of Education (Tech), Potiskum",
    "Nasarrawa State College of Education, Akwanga",
    "Isa Kaita College of Education, Dutsin-Ma",
    "College of Education, Ekiadolor-Benin",
    "College of Education, Gashua, Damaturu",
    "Kaduna State College of Education, Gidan-Waya, Kafanchan",
    "Osun State College of Education, Ilesa",
    "College of Education Oro",
    "College of Education, katsina-Ala",
    "Sa`adatu Rimi College of Education, Kumbotso, Kano",
    "College of Education (Technical), Lafiagi",
    "Nwafor Orizu College of Education, Nsugbe",
    "Adeniran Ogunsanya College of Education, Otto/Ijanikin",
    "Alvan Ikoku College of Education, Owerri",
    "Emmanuel Alayande College of Education (EACOED), Oyo",
    "College of Education, Waka BIU",
    "City College of Education, Mararaba",
    "Federal College of Education (Technical), Akoka",
    "Federal College of Education (Technical), Bichi",
    "Federal College of Education (Technical), Gusau",
    "Federal College of Education, Katsina",
    "Federal College of Education, Obudu",
    "Adeyemi College of Education, Ondo",
    "Federal College of Education, Pankshin",
    "Federal College of Education, Yola",
    "Delta State College of Education, Agbor",
    "Federal College of Education, Zaria",
    "Akwa Ibom State College of Education, Afahansit",
    "Kogi State College of Education, Ankpa",
    "Adamu Augie College of Education, Argungu",
    "Aminu Sale College of Education, Azare",
    "Umar Ibn Ibrahim El-Kanemi College of Education, Science and Technology, Bama",
    "Nigerian Army School of Education (NASE), Ilorin",
    "Zamfara State College of Education, Maru",
    "Jigawa State College of Education, Gumel",
    "Niger State College of Education, Minna",
    "Shehu Shagari College of Education, Sokoto",
    "Ansar-Ud-Deen College of Education, Isolo",
    "Yewa Central College of Education, Ayetoro, Abeokuta",
    "Federal College of Education (T), Umunze",
    "College of Education, Arochukwu, Abia",
    "College of Education, Ila-Orangun, Osun State",
    "Michael Otedola Coll. of Prim. Education, Lagos",
    "Kashim Ibrahim College of Education",
    "Delta State Coll. of Physical Education, Mosogar",
    "Enugu State Coll. of Education (T), Enugu",
    "Cross River State Coll. of Education, Akampa",
    "Edo State College of Education, Igueben",
    "Isaac Jasper Boro COE, Sagbama",
    "Kogi State College of Education, Kabba",
    "Osisa Tech. College of Education, Enugu",
    "St. Augustine College of Education Akoka, Lagos",
    "African Thinkers Community of Inquiry COE, Enugu",
    "Muftau Olanihun College of Education, Ibadan",
    "Havard Wilson College of Education, Aba",
    "Muhyideen College of Education, Ilorin",
    "Corner Stone College of Education, Ikeja",
    "Peaceland College of Education, Enugu",
    "The College of Education, Nsukka",
    "Unity College of Education, Aukpa Adoka, Benue",
    "DIAMOND COLLEGE OF EDUCATION, ABA",
    "National Teachers Institute(NTI)",
    "Kingsey College of Education, Ilorin, Kwara State",
    "ECWA College of Education, Jos (ECOEJ)",
    "FESTMED COLLEGE OF EDUCATION, ONDO STATE",
    "BETHEL COE IJARE, ONDO",
    "STEADY FLOW COE, IKOM",
    "AL HIKMA COLLEGE OF EDUCATION, ANKPA",
    "Global COE, Bukuru",
    "Kwararafa COE, Otukpo",
    "College of Education, Billiri",
    "Lessel COE Gboko",
    "Bayo Tijani COE, Lagos",
    "Upland COE Badagry",
    "College of Education, Zing",
    "ECWA COE Igbaja",
    "PAN African COE Offa",
    "Corona COE Lekki",
    "College of Education Oju",
    "EEICOE Otukpo",
    "Sinai COE & Ent. Studies Gboko, Benue",
    "MCF COE Agbarha-Otor, Delta",
    "Assanusiya COE, Odeomu, Osun",
    "COE, Ero, Akure",
    "Calvin Foundation COE",
    "Best Legacy COE Ogbomoso",
    "Angel Crown COE",
    "Elder Oyama Memorial COE, Ofat",
    "COE, Moro, Ife-North",
    "Royal City COE, Iyesi-Ota",
    "ONIT COE, Abagana",
    "Nana Aishat Memorial COE",
    "Top-Most COE, Ipaja-Agbado",
    "Apa COE, Aido",
    "Awori District COE",
    "Hill COE, Gwanje, Akwanga",
    "Aminu Kano College of Education",
    "Murtadha COE, Olodo",
    "Islamic COE, Potiskum",
    "Royal COE, Ikeja, Lagos State",
    "Hassan Usman Katsina Polytechnic",
    "Plateau State Polytechnic",
    "Kano State Polytechnic",
    "Waziri Umaru Federal Polytechnic",
    "Ramat Polytechnic",
    "Kaduna Polytechnics",
    "Abubakar Tatari Polytechnic",
    "Nuhu Bamalli Polytechnic",
    "Ipere COE, Agyaragu",
    "Piaget College of Education",
    "Biga College of Education",
    "Al-Ibadan COE",
    "College of Education Kura",
    "Sunnah College of Education",
    "Oswald Waller COE Shendam",
    "Imam Saidu COE, Funtua",
    "Bilyaminu Othman COE Dass",
    "The Polytechnic Iree, Osun State",
    "Bogoro College of Education",
    "Adesina College of Education, Share, Kwara State",
    "Covenant College of Education (CCOE)",
    "JIGAWA STATE COLLEGE OF EDUCATION AND LEGAL STUDIES, RINGIM",
    "CRESTFIELD COLLEGE OF EDUCATION",
    "GRACE COLLEGE OF EDUCATION",
    "AFRICAN CHURCH COLLEGE OF EDUCATION",
    "Kano State College of Education and Remedial Studies, Kano",
    "College of Education, Lanlate, Oyo State",
    "Climax College of Education, Bauchi",
    "College of Education and Legal Studies",
    "Federal College of Education Sokoto",
    "Federal College of Education Bauchi",
    "Federal College of Education (T), ISU Ebonyi State",
    "Federal College of Education, Odugbo, Benue State",
    "Federal College of Education Osun",
    "Federal College of Education Edo",
    "Kashim Ibrahim College of Education",
    "College of Education Oro",
    "Imo State College of Education, Ihitte/Uboma",
    "Annur College of Education Kano",
    "College of Education Ilemona",
    "Ebenezer College of Education Amangwu",
    "JIBWIS College of Education Gombe",
    "Kogi East College of Education",
    "Gboko College of Education Benue State",
    "Hope and Anchor College of Education",
    "Elizabeth Memorial College of Education Nsukka",
    "Ilori College of Education , Ede",
    "Sarkin Yama Community College of Education",
    "Umar Bun Khatab College of Education, Tudun Nupawa, Kaduna",
    "Peacock College of Education Jalingo",
    "Peace College Of Education Ankpa",
    "Moje College of Education, Erin-Ile",
    "Uli College of Education, Uli",
    "Lifegate College of Education, Asa",
    "JIBWIS COE, Jamaare",
    "Dala College of Education, Kano",
    "Hamzainab College of Education, Oshogbo",
    "College of Education, Darazo",
    "Abubakar Garba Zagada- Zagada College of Education, Bajoga",
    "Imam Hamzat COE, Ilorin",
    "Metro COE, Adogi-Lafia",
    "College of Sharia and Arabic Studies",
    "Abdullahi Maikano College of Education, Wase",
    "Nosakhare COE, Benin City",
    "Good Shepperd COE",
    "Turath COE, Kano",
    "Meadow Hall COE",
    "Raphat COE",
    "Kazaure College of Education",
    "JIBWIS College of Education",
    "Adamu Garkuwa COE, Toro",
    "Folrac Fortified COE, Ondo",
    "Al-Iman College of Education",
    "Danyaya College of Education, Ningi",
    "Innovative College of Education, Karu",
    "Sam Ale College of Education",
    "Gombe State COE, NAFADA",
    "Gand-Plus College of Education",
    "Olekamba College of Education",
    "Emamo College of Education",
    "Aminu Kano College of Islamic and Legal Studies",
    "Muhammad Goni College of Legal and Islamic Studies (MOGOLIS)",
    "A.D. Rufai College for Islamic and Legal Studies",
    'Yusuf Bala Usman College of Legal and General Studies, Daura'
        "Bauchi Institute for Arabic and Islamic Studies",
    "Institute of Ecumenical Education (Thinkers Corner)",
    "Ameer Shehu Idris College of Advanced Studies, Zaria",
    "National Institute for Nigerian Languages (NINLAN)",
  ];

  static const List<String> allSchools = [
    ...universities,
    ...polytechnics,
    ...collegeOfEducation,
    ...healthSciences
  ];
}
